### PR TITLE
Added DoSlowCmd and DoGAPFunc functions

### PR DESCRIPTION
**Pull request by SgtB33L**
DoSlowCmd and DoGAPFunc were added to use GAPTRANSFERPROSPERIPR OpenServer function

### CODE REVIEW

**Comment by smolvik1** [comment]
Hi!
Could you elaborate a bit on the need for implementing these functions? From 1.1 in Openserver Manual the need for DoSlowCmd seems to stem from timeout issues in Excel and/or license server traffic issues.

**Comment by MTrevoux** [comment]
Good morning!

1/ I confirm that Python has no issues with timeouts which is the case with VBA.
2/ Was the DoGAPFunc tested? 
In addition, this new block should check if the connection is made prior to running and include a "try" block. If you use this function as it is in a program, it may break.
3/ Finally a description should be added using the '''.

If I can give any additional help let me know.

**Comment by knudsvik** [comment]
I am pretty sure these functions are not needed when using Python and should thus not be implemented. If, however, they need to be implemented, docstrings and testing are needed as @MTrevoux points out.

**Comment by SgtB33L** [comment]
@smolvik1, @MTrevoux, @knudsvik  you are all correct.  I translated the functions from VBA example and wrongfully assumed the timeout issue was related to PETEX and not Excel.  Guess I should have started at the beginning of the manual.  As a bonus my test case now runs quicker using DoCmd to transfer the IPRs.  Thank you for the quick replies and the brilliant work creating the package.  Cheers

**Pull request closed without merging**
