### PR TITLE
M trevoux patch 1

### PR DESCRIPTION
**Pull request by MTrevoux**
Hello,

Adding context manager for dealing with connections avoiding blockage of licenses.

Testing below:
image

### CODE REVIEW

**Comment by knudsvik** [comment]
Not sure I understand the purpose of this PR. The initial class has methods to connect and disconnect to free up the license. If an exception is thrown, the disconnect method is run and license free'd up?

**Comment by MTrevoux** [comment]
Hi Thorjan,

There are several advantages of using a such a context:

The exceptions you are mentioning are the ones happening when using the DoGet, DoSet or DoCmd methods.
However if you make an error outside from those methods, you keep the connection open.
See the example below:
image

In this example one leaves the connection open and can lock it if the instance is killed. The context manager on the other hand is automatically closing the connection in such cases. It happens to be very useful when using notebooks and testing codes. 
It also saves you if case you forget to disconnect after few line of codes...

Finally, in terms of scripting you need a single line of code to create the instance, connect and deal with disconnection whereas in the actual case you need 3:

```
With OSconnection() as c:
    ...Do stuff...

#Versus

c = OpenServer()
c.connect()
...Do Stuff...
c.disconnect()
```
  
I hope it makes sense

**Comment by knudsvik** [comment]
Hi, the use of `with` statements is quite new to us, but we see how this could improve certain use cases. Would it be possible to include the `__enter__` and `__exit__` method directly in the `OpenServer` class instead? So instantiating it by
`with OpenServer as c:
   c.DoSet() ...`

**Comment by MTrevoux** [comment]
Hi,
Sure I will look at how to include it in the main class. I need to check few things there.

For the use cases, I see two of them:
- Notebook development with trial and error testing
- When you see a block like below which is an equivalent:

```
c = OpenServer()
c.connect()
try:
   ... Do things ...
except:
   c.disconnect()
```

I will keep you posted in the coming days.

**Comment by MTrevoux** [comment]
Ok, all done and giving the same results:

You can see in the screen shot below that the with statement is working when declaring the OpenServer() instance. 

image

**Review by knudsvik — APPROVED** [review]

**Comment by knudsvik** [comment]
Looks good! Please update version.py and changelog.md and I can merge it afterwards.

**Comment by knudsvik** [comment]
Thank you very much for your contribution :)

**Comment by MTrevoux** [comment]
With pleasure!

**Comment by knudsvik** [comment]
The new version is now available on PyPi as well so you can run `pip install openserver --upgrade` to patch your installation!

**Pull request merged**
